/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DestinationsDestinationSlugRouteImport } from './routes/destinations.$destinationSlug'
import { Route as ExplorePassportSlugRouteImport } from './routes/explore.$passportSlug'
import { Route as PassportsPassportSlugRouteImport } from './routes/passports.$passportSlug'
import { Route as CompareFirstPassportSlugSecondPassportSlugRouteImport } from './routes/compare.$firstPassportSlug.$secondPassportSlug'
import { Route as VisaPassportSlugDestinationSlugRouteImport } from './routes/visa.$passportSlug.$destinationSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsDestinationSlugRoute =
  DestinationsDestinationSlugRouteImport.update({
    id: '/destinations/$destinationSlug',
    path: '/destinations/$destinationSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExplorePassportSlugRoute = ExplorePassportSlugRouteImport.update({
  id: '/explore/$passportSlug',
  path: '/explore/$passportSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportsPassportSlugRoute = PassportsPassportSlugRouteImport.update({
  id: '/passports/$passportSlug',
  path: '/passports/$passportSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareFirstPassportSlugSecondPassportSlugRoute =
  CompareFirstPassportSlugSecondPassportSlugRouteImport.update({
    id: '/compare/$firstPassportSlug/$secondPassportSlug',
    path: '/compare/$firstPassportSlug/$secondPassportSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const VisaPassportSlugDestinationSlugRoute =
  VisaPassportSlugDestinationSlugRouteImport.update({
    id: '/visa/$passportSlug/$destinationSlug',
    path: '/visa/$passportSlug/$destinationSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/destinations/$destinationSlug': typeof DestinationsDestinationSlugRoute
  '/explore/$passportSlug': typeof ExplorePassportSlugRoute
  '/passports/$passportSlug': typeof PassportsPassportSlugRoute
  '/compare/$firstPassportSlug/$secondPassportSlug': typeof CompareFirstPassportSlugSecondPassportSlugRoute
  '/visa/$passportSlug/$destinationSlug': typeof VisaPassportSlugDestinationSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/destinations/$destinationSlug': typeof DestinationsDestinationSlugRoute
  '/explore/$passportSlug': typeof ExplorePassportSlugRoute
  '/passports/$passportSlug': typeof PassportsPassportSlugRoute
  '/compare/$firstPassportSlug/$secondPassportSlug': typeof CompareFirstPassportSlugSecondPassportSlugRoute
  '/visa/$passportSlug/$destinationSlug': typeof VisaPassportSlugDestinationSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/destinations/$destinationSlug': typeof DestinationsDestinationSlugRoute
  '/explore/$passportSlug': typeof ExplorePassportSlugRoute
  '/passports/$passportSlug': typeof PassportsPassportSlugRoute
  '/compare/$firstPassportSlug/$secondPassportSlug': typeof CompareFirstPassportSlugSecondPassportSlugRoute
  '/visa/$passportSlug/$destinationSlug': typeof VisaPassportSlugDestinationSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/destinations/$destinationSlug'
    | '/explore/$passportSlug'
    | '/passports/$passportSlug'
    | '/compare/$firstPassportSlug/$secondPassportSlug'
    | '/visa/$passportSlug/$destinationSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/destinations/$destinationSlug'
    | '/explore/$passportSlug'
    | '/passports/$passportSlug'
    | '/compare/$firstPassportSlug/$secondPassportSlug'
    | '/visa/$passportSlug/$destinationSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/destinations/$destinationSlug'
    | '/explore/$passportSlug'
    | '/passports/$passportSlug'
    | '/compare/$firstPassportSlug/$secondPassportSlug'
    | '/visa/$passportSlug/$destinationSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DestinationsDestinationSlugRoute: typeof DestinationsDestinationSlugRoute
  ExplorePassportSlugRoute: typeof ExplorePassportSlugRoute
  PassportsPassportSlugRoute: typeof PassportsPassportSlugRoute
  CompareFirstPassportSlugSecondPassportSlugRoute: typeof CompareFirstPassportSlugSecondPassportSlugRoute
  VisaPassportSlugDestinationSlugRoute: typeof VisaPassportSlugDestinationSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$destinationSlug': {
      id: '/destinations/$destinationSlug'
      path: '/destinations/$destinationSlug'
      fullPath: '/destinations/$destinationSlug'
      preLoaderRoute: typeof DestinationsDestinationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$passportSlug': {
      id: '/explore/$passportSlug'
      path: '/explore/$passportSlug'
      fullPath: '/explore/$passportSlug'
      preLoaderRoute: typeof ExplorePassportSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passports/$passportSlug': {
      id: '/passports/$passportSlug'
      path: '/passports/$passportSlug'
      fullPath: '/passports/$passportSlug'
      preLoaderRoute: typeof PassportsPassportSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$firstPassportSlug/$secondPassportSlug': {
      id: '/compare/$firstPassportSlug/$secondPassportSlug'
      path: '/compare/$firstPassportSlug/$secondPassportSlug'
      fullPath: '/compare/$firstPassportSlug/$secondPassportSlug'
      preLoaderRoute: typeof CompareFirstPassportSlugSecondPassportSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visa/$passportSlug/$destinationSlug': {
      id: '/visa/$passportSlug/$destinationSlug'
      path: '/visa/$passportSlug/$destinationSlug'
      fullPath: '/visa/$passportSlug/$destinationSlug'
      preLoaderRoute: typeof VisaPassportSlugDestinationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DestinationsDestinationSlugRoute: DestinationsDestinationSlugRoute,
  ExplorePassportSlugRoute: ExplorePassportSlugRoute,
  PassportsPassportSlugRoute: PassportsPassportSlugRoute,
  CompareFirstPassportSlugSecondPassportSlugRoute:
    CompareFirstPassportSlugSecondPassportSlugRoute,
  VisaPassportSlugDestinationSlugRoute: VisaPassportSlugDestinationSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
